// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: box_paths.sql

package database

import (
	"context"
)

const addBoxPath = `-- name: AddBoxPath :one
INSERT INTO box_paths (box_id, path)
VALUES (?, ?)
RETURNING id, box_id, path
`

type AddBoxPathParams struct {
	BoxID int64
	Path  string
}

func (q *Queries) AddBoxPath(ctx context.Context, arg AddBoxPathParams) (BoxPath, error) {
	row := q.db.QueryRowContext(ctx, addBoxPath, arg.BoxID, arg.Path)
	var i BoxPath
	err := row.Scan(&i.ID, &i.BoxID, &i.Path)
	return i, err
}

const listAllBoxPaths = `-- name: ListAllBoxPaths :many
SELECT id, box_id, path FROM box_paths ORDER BY box_id, id
`

func (q *Queries) ListAllBoxPaths(ctx context.Context) ([]BoxPath, error) {
	rows, err := q.db.QueryContext(ctx, listAllBoxPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoxPath
	for rows.Next() {
		var i BoxPath
		if err := rows.Scan(&i.ID, &i.BoxID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoxPaths = `-- name: ListBoxPaths :many
SELECT id, box_id, path FROM box_paths WHERE box_id = ? ORDER BY id
`

func (q *Queries) ListBoxPaths(ctx context.Context, boxID int64) ([]BoxPath, error) {
	rows, err := q.db.QueryContext(ctx, listBoxPaths, boxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoxPath
	for rows.Next() {
		var i BoxPath
		if err := rows.Scan(&i.ID, &i.BoxID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBoxPath = `-- name: RemoveBoxPath :exec
DELETE FROM box_paths WHERE id = ?
`

func (q *Queries) RemoveBoxPath(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, removeBoxPath, id)
	return err
}

const removeBoxPathByPath = `-- name: RemoveBoxPathByPath :exec
DELETE FROM box_paths WHERE box_id = ? AND path = ?
`

type RemoveBoxPathByPathParams struct {
	BoxID int64
	Path  string
}

func (q *Queries) RemoveBoxPathByPath(ctx context.Context, arg RemoveBoxPathByPathParams) error {
	_, err := q.db.ExecContext(ctx, removeBoxPathByPath, arg.BoxID, arg.Path)
	return err
}
