// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: boxes.sql

package database

import (
	"context"
)

const createBox = `-- name: CreateBox :one
INSERT INTO boxes (title, path)
VALUES (?, ?)
RETURNING id, title, path
`

type CreateBoxParams struct {
	Title string
	Path  string
}

func (q *Queries) CreateBox(ctx context.Context, arg CreateBoxParams) (Box, error) {
	row := q.db.QueryRowContext(ctx, createBox, arg.Title, arg.Path)
	var i Box
	err := row.Scan(&i.ID, &i.Title, &i.Path)
	return i, err
}

const deleteBox = `-- name: DeleteBox :exec
DELETE FROM boxes
WHERE id = ?
`

func (q *Queries) DeleteBox(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteBox, id)
	return err
}

const listBoxes = `-- name: ListBoxes :many
SELECT id, title, path FROM boxes ORDER BY id
`

func (q *Queries) ListBoxes(ctx context.Context) ([]Box, error) {
	rows, err := q.db.QueryContext(ctx, listBoxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Box
	for rows.Next() {
		var i Box
		if err := rows.Scan(&i.ID, &i.Title, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBox = `-- name: UpdateBox :one
UPDATE boxes
SET title = ?, path = ?
WHERE id = ?
RETURNING id, title, path
`

type UpdateBoxParams struct {
	Title string
	Path  string
	ID    int64
}

func (q *Queries) UpdateBox(ctx context.Context, arg UpdateBoxParams) (Box, error) {
	row := q.db.QueryRowContext(ctx, updateBox, arg.Title, arg.Path, arg.ID)
	var i Box
	err := row.Scan(&i.ID, &i.Title, &i.Path)
	return i, err
}
