// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: boxes.sql

package database

import (
	"context"
)

const deleteBox = `-- name: DeleteBox :exec
DELETE FROM boxes WHERE id = ?
`

func (q *Queries) DeleteBox(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteBox, id)
	return err
}

const getBoxByID = `-- name: GetBoxByID :one
SELECT id, title, path, active FROM boxes WHERE id = ?
`

func (q *Queries) GetBoxByID(ctx context.Context, id string) (Box, error) {
	row := q.db.QueryRowContext(ctx, getBoxByID, id)
	var i Box
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Path,
		&i.Active,
	)
	return i, err
}

const listBoxes = `-- name: ListBoxes :many
SELECT id, title, path, active FROM boxes ORDER BY title
`

func (q *Queries) ListBoxes(ctx context.Context) ([]Box, error) {
	rows, err := q.db.QueryContext(ctx, listBoxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Box
	for rows.Next() {
		var i Box
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Path,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoxesByActive = `-- name: ListBoxesByActive :many
SELECT id, title, path, active FROM boxes WHERE active = ? ORDER BY title
`

func (q *Queries) ListBoxesByActive(ctx context.Context, active bool) ([]Box, error) {
	rows, err := q.db.QueryContext(ctx, listBoxesByActive, active)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Box
	for rows.Next() {
		var i Box
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Path,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoxesByPath = `-- name: ListBoxesByPath :many
SELECT id, title, path, active FROM boxes WHERE path = ?
`

func (q *Queries) ListBoxesByPath(ctx context.Context, path string) ([]Box, error) {
	rows, err := q.db.QueryContext(ctx, listBoxesByPath, path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Box
	for rows.Next() {
		var i Box
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Path,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBox = `-- name: UpsertBox :one
INSERT INTO boxes (id, title, path, active)
VALUES (?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE
SET title = excluded.title, path = excluded.path, active = excluded.active
RETURNING id, title, path, active
`

type UpsertBoxParams struct {
	ID     string
	Title  string
	Path   string
	Active bool
}

func (q *Queries) UpsertBox(ctx context.Context, arg UpsertBoxParams) (Box, error) {
	row := q.db.QueryRowContext(ctx, upsertBox,
		arg.ID,
		arg.Title,
		arg.Path,
		arg.Active,
	)
	var i Box
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Path,
		&i.Active,
	)
	return i, err
}
