// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type Box struct {
	ID        int64
	Title     string
	Path      string
	DeletedAt sql.NullTime
}

type BoxPath struct {
	ID    int64
	BoxID int64
	Path  string
}
