# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  dev:
    desc: Run the TUI app in development mode
    cmd: APP_ENV=development go run ./cmd/notebox/

  build:
    desc: Build the TUI
    cmds:
      - go build -o notebox cmd/notebox/main.go

  clean:
    desc: Clean the Binary
    cmds:
      - rm ./notebox

  release:
    desc: Release the CLI binary in local
    cmds:
      - goreleaser check
      - goreleaser release --snapshot --clean

  fmt:
    desc: go fmt
    cmd: go fmt ./...

  test:
    desc: Run all tests
    cmds:
      - go test -v ./internal/...
